language: php

dist: bionic

php:
  - 7.3

before_install:
  - sudo apt-get -y install gcc librdkafka1 librdkafka-dev scala zookeeperd
  - wget https://www-eu.apache.org/dist/kafka/2.3.0/kafka_2.11-2.3.0.tgz
  - tar zxf kafka_2.11-2.3.0.tgz

install:
  - pecl install rdkafka
  - composer self-update
  - composer install

before_script:
  - nohup kafka_2.11-2.3.0/bin/kafka-server-start.sh kafka_2.11-2.3.0/config/server.properties > kafka_2.11-2.3.0/kafka.log 2>&1 &
  - sleep 5

script:
  - make build
