language: php

dist: bionic

php:
  - 7.3

before_install:
  - sudo apt-get update && apt-get -y install gcc librdkafka1 librdkafka-dev scala zookeeperd
  - wget http://mirrors.gigenet.com/apache/kafka/0.9.0.1/kafka_2.11-0.9.0.1.tgz
  - tar zxf kafka_2.11-0.9.0.1.tgz

install:
  - pecl install rdkafka
  - composer self-update
  - composer install

before_script:
  - nohup kafka_2.11-0.9.0.1/bin/kafka-server-start.sh kafka_2.11-0.9.0.1/config/server.properties > kafka_2.11-0.9.0.1/kafka.log 2>&1 &
  - sleep 5

script:
  - make build
